/*
******************************************************************************
File:     main.c
Info:     Generated by Atollic TrueSTUDIO(R) 9.0.1   2018-08-17

The MIT License (MIT)
Copyright (c) 2018 STMicroelectronics

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.

******************************************************************************
*/

/* Includes */
#include "stm32f4xx.h"
#include "logging.h"
#include "I2C.h"
#include "control_loop.h"
#include "encoder.h"
#include "IMU.h"
#include "EKF.h"




/* Private macro */
/* Private variables */
  uint32_t count;
  int16_t raw_acc[3]; //xyz
  int16_t raw_gyro[3]; //xyz
  uint8_t raw_temp[2];
  uint32_t loop_count;
  float	sensor_values[4];
  float states[3];
  float covar_mat[9];





/* Private function prototypes */
/* Private functions */
/*
 * PA9 - Tx
 * PA10 - Rx
 * PA15 TIM2_CH1
 * PB3 TIM2_CH2
 * PA8 I2C_SCL
 * PC9 I2C_SDA
*/
/**
**===========================================================================
**
**  Abstract: main program
**
**===========================================================================
*/


int main(void){

  count = 0;
  loop_count = 0;
  SystemInit();

  // Init and config IMU - MPU
  init_I2C3();
  MPU_Init(I2C3);

  USART_LoggingInit();
  ENCODER_Init();
  Control_LoopInit();
  states[0] = 0;
  states[1] = 0;
  states[2] = 0;



  /* Infinite loop */
  while (1){
	  loop_count++;

	  // Receive values from encoder and IMU
	  count = TIM_GetCounter(TIM2);
	  sensor_values[3] = (float)(count-ENCODER_START_VALUE)/(ENCODER_GAIN*N);

	  MPU_GetAccGyro(I2C3, raw_acc, raw_gyro, raw_temp);
	  sensor_values[0] = ((float)raw_acc[0]/ACC_GAIN-X_OFFSET)/X_SCALE;
	  sensor_values[1] = ((float)raw_acc[1]/ACC_GAIN-Y_OFFSET)/Y_SCALE;
	  sensor_values[2] = ((float)raw_gyro[2]/GYRO_GAIN-GYRO_OFFSET)/GYRO_SCALE;

	  // Perform EKF calculations
	  // predict X
	  X_Predict();
	  //predict P
	  P_Predict();

	  // Update
	  //Pack Z
	  // anticlockwise from positive x axis on cart. plane not IMU axis
	  // acc_norm = acc_y, acc_tang = acc_x, gyro_vel = gyro_z

	  Z_Pack(sensor_values);
//	  Z_Pack(0,981,0,count);

	  //Pack H
	  H_Pack();

	  // calc Y
	  Y_Calc();

	  H_JacobianCalc();

	  // calc K
	  K_Calc();
	  //Update X
	  X_Update();
	  //P_Update
	  P_Update();

	  EKF_RetrieveStates(states);



	  // acc_norm = acc_x, acc_tang = acc_y, gyro_vel = gyro_z
	  LOG_CombineData(loop_count, raw_acc[0], raw_acc[1], raw_gyro[2], count, raw_temp, states);
//	  states[0] = -7;
//	  states[1] = 8;
//	  states[2] = -9;
//	  LOG_CombineData(12121,-8192,8192,-16400,0x7fffffff,raw_temp,states);


	  wait_for_restart();
  }
}

